server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "autenticacion"
    username: "root"
    password: "r@ot25"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/usuarios
