server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,loggers"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "autenticacion"
    username: "root"
    password: "r@ot25"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/usuarios

logging:
  level:
    co.com.pragma: DEBUG

jwt:
  secret: b96fdf257931365584ac4eb5e93add39fabd52a5cd7297a5918b0c0204d76e3f
  expiration: 3600000
